clear all
clear java
close all
clc

passengerVehicle = sumolib.demand.VehicleType('twingo', 'accel', 14.5, 'decel',...
    35.8, 'sigma', 0.5, 'tau', 1, 'length', 3.6, 'minGap', 1.5, 'maxSpeed',...
    151, 'speedFactor', 1, 'speedDev', 0, 'color', [168 181 181],...
    'vClass', 'passenger', 'emissionClass', 'P_7_7', 'guiShape', 'passenger',...
    'width', 1.64, 'imgFile', '', 'impatience', 0, 'laneChangeModel', 'DK2008',...
    'personCapacity', 4, 'containerCapacity', 0, 'boardingDuration', 2,...
    'loadingDuration', 20);

twingoFlow = sumolib.demand.Flow('twingoFlow', 300, 'endTime', 500, 'type',...
    passengerVehicle, 'from', '33463249#0_0', 'to', '33463249#3_0',...
    'via', '33463249#1_0', 'vehsPerHour', 300, 'number', 900, 'color',...
    [120 55 0], 'departLane', 'random', 'departPos', 'base', 'departSpeed',...
    'random', 'arrivalLane', 'current', 'arrivalPos', 'max', 'arrivalSpeed',...
    'current');